[book]
authors = ["CRC-team"]
language = "en"
multilingual = false
src = "content"
title = "CRC Engineering docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"

[preprocessor.callouts]

[preprocessor.kroki]
