name: Build and publish docs

on:
  push:
    branches:
      - "main"
  pull_request: {}
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Build docs
        run: podman run --rm -v $PWD:/workspace ghcr.io/crc-org/mdbook:latest build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
